### ISSUE TITLE
No import of Autodesk Inventor SAT possible

### ISSUE THREAD

**Issue by richardklingler** [ijacquez/trsat#1]
Installed on blender 2.79b on macOS 10.13.6...

Importing a .sat file shows no errors nor any other information....
Is this plugin for the same .sat format as Inventor produces or another .sat format?

**Comment by ijacquez** [comment]
This was only tested on a US release of Tomb Raider for Saturn.

I'm unsure what Inventor is. 

Edit: The .SAT format is a format exclusive to TR for the Saturn. Autodesk is not supported at all.
